[package]
name = "dfir-toolkit"
version = "0.3.0"
edition = "2021"
authors = ["Jan Starke <Jan.Starke@telekom.de>"]
description = "CLI tools for digital forensics and incident response"
homepage = "https://www.github.com/janstarke/dfir_toolkit"
license = "GPL-3.0"

[[bin]]
name = "mactime2"
required-features = ["mactime2"]

[[bin]]
name = "evtxscan"
required-features = ["evtxscan"]

[[bin]]
name = "evtxcat"
required-features = ["evtxcat"]

[[bin]]
name = "evtxls"
required-features = ["evtxls"]

[[bin]]
name = "evtxanalyze"
required-features = ["evtxanalyze"]

[[bin]]
name = "pol_export"
required-features = ["pol_export"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["pol_export", "mactime2", "evtxtools"]
mactime2 = ["gzip", "elastic", "chrono-tz", "thiserror", "bitflags", "encoding_rs_io"]
gzip = ["flate2"]
elastic = ["es4forensics", "serde_json"]
evtxtools = ["evtxscan", "evtxcat", "evtxls", "evtxanalyze"]
pol_export = []
evtxscan = ["evtx"]
evtxcat = ["evtx", "colored_json", "term-table", "termsize"]
evtxls = ["evtx", "colored", "lazy-regex", "regex", "sigpipe", "dfirtk-eventdata"]
evtxanalyze = ["evtx", "dfirtk-sessionevent-derive", "dfirtk-eventdata"]

[dependencies]
anyhow = "1.0"
binread = "2.2.0"
chrono = "0.4"
clap = {version = "4.3", features = ["derive", "wrap_help", "cargo"] }
clap-verbosity-flag = "2.0.0"
csv = "1.2.2"
encoding_rs = "0.8"
log = {version = "0.4", features = [ "release_max_level_info" ]}
serde = { version = "1.0", features = ["derive"] }
simplelog = "0.12"
winstructs = "0.3.0"
bodyfile = "0.1"

# mactime2
chrono-tz = {version="0.8", optional=true}
es4forensics = {version="0.5.1", optional=true, default-features=false}
serde_json = {version = "1", optional=true}
flate2 = {version="1", optional=true}
thiserror = {version="1", optional=true}
bitflags = {version="2", optional=true}
encoding_rs_io = {version="0.1", optional=true}

# evtxtools
dfirtk-eventdata = {version="0.1.2", optional=true}
dfirtk-sessionevent-derive = {version="0.1", optional=true}
evtx={version="0.8", optional=true}
colored_json = {version="3", optional=true}
term-table = {version = "1.3", optional=true}
termsize = {version = "0.1", optional=true}
regex = {version = "1", optional=true}
colored = {version = "2", optional=true}
lazy-regex = {version = "3.0.0", optional=true}
sigpipe = {version = "0", optional=true}
phf = {version = "0.11", optional=true}

[dev-dependencies]

# mactime2
more-asserts = "0.3"
rand = "0.8"
