[package]
name = "dfir-toolkit"
version = "0.2.1"
edition = "2021"
authors = ["Jan Starke <Jan.Starke@telekom.de>"]
description = "CLI tools for digital forensics and incident response"
homepage = "https://www.github.com/janstarke/dfir_toolkit"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["gzip", "elastic"]
gzip = ["flate2"]
elastic = ["es4forensics", "serde_json"]

[dependencies]
anyhow = "1.0"
binread = "2.2.0"
chrono = "0.4"
clap = {version = "4.3", features = ["derive"] }
clap-verbosity-flag = "2.0.0"
csv = "1.2.2"
encoding_rs = "0.8"
log = {version = "0.4", features = [ "release_max_level_info" ]}
serde = { version = "1.0", features = ["derive"] }
simplelog = "0.12"
winstructs = "0.3.0"

# mactime2
chrono-tz = "0.8"
es4forensics = {version="0.5.1", optional=true, default-features=false}
serde_json = {version = "1", optional=true}
flate2 = {version="1", optional=true}
thiserror = "1"
bodyfile = "0.1"
bitflags = "2"
encoding_rs_io = "0.1"

[dev-dependencies]

# mactime2
more-asserts = "0.3"
rand = "0.8"
