on: [push]

name: Run automatic tests

jobs:
  build_and_test:
    name: Run automatic tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install required libscca-dev
        run: sudo apt install -y libscca-dev

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features