name: publish at crates.io
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        
        - name: Install required libscca-dev
          run: sudo apt install -y libscca-dev
          
        - uses: actions-rs/toolchain@v1
          with:
              toolchain: stable
              override: true
        - uses: katyo/publish-crates@v1
          with:
              registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
